[package]
name = "ang/test"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
jecs = "ukendio/jecs@0.6.1"  # 建议访问其 [Wally页面](https://wally.run/package/ukendio/jecs) 确认最新版本号